2025-08-23 14:10:29,764 - causalllm.llm_client.openai - INFO - __init__:17 - Initializing OpenAI client
2025-08-23 14:10:30,056 - causalllm.llm_client.openai - ERROR - __init__:30 - Invalid OpenAI credentials - using default placeholders
2025-08-23 14:10:30,056 - causalllm.llm_client.openai - INFO - __init__:17 - Initializing OpenAI client
2025-08-23 14:10:30,056 - causalllm.llm_client.openai - ERROR - __init__:30 - Invalid OpenAI credentials - using default placeholders
